### ISSUE TITLE
Errors during async requests are uncatchable

### ISSUE THREAD

**Issue by ProPuke** [yupswing/akifox-asynchttp#14]
Any errors during an async request (with `errorSafe` off) are thrown as uncatchable exceptions (because in a separate thread) and immediately terminate the program.

It would be nice if exceptions were caught internally, and `callback` or `callbackError` was still called with exception object included.

**Comment by yupswing** [comment]
You are absolutely right.
I put this on next release.

Anyway the idea beside this problem I didn't see (because I've never tested it this way) is to use errors only on debug stage since every problem is handled by the library and it will return a status 0 response on a request with errors.

Thanks for reporting the issue ;)
